config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('medicines/', include('medicines.urls')),
    path('accounts/', include('accounts.urls')),
]

medicines/urls.py
from django.urls import path
from .views import medicine_list, medicine_create, medicine_detail, medicine_edit, medicine_delete

app_name = 'medicines'

urlpatterns = [
    path('', medicine_list, name='list'),
    path('add/', medicine_create, name='create'),
    path('<int:pk>/', medicine_detail, name='detail'),
    path('<int:pk>/edit/', medicine_edit, name='edit'),
    path('<int:pk>/delete/', medicine_delete, name='delete'),
]

medicines/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Medicine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    dosage = models.CharField(max_length=120)
    frequency = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('medicines:detail', kwargs={'pk': self.pk})

medicines/forms.py
from django import forms

from medicines.models import Medicine


class MedicineForm(forms.ModelForm):
    class Meta:
        model = Medicine
        fields = ['user', 'name', 'dosage', 'frequency']

medicines/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView
)

from medicines.forms import MedicineForm
from medicines.models import Medicine
from .decorators import check_for_owner


@login_required
def medicine_create(request):
    form = MedicineForm(request.POST or None)
    context = {"form": form}
    if form.is_valid():
        medicine_object = form.save()
        context['form'] = MedicineForm()
        context['object'] = medicine_object
        context['created'] = True
        return render(request, "medicines/create.html", context=context)
    return render(request, "medicines/create.html", context=context)


class MedicineDetailView(DetailView):
    model = Medicine
    context_object_name = 'medicine'
    template_name = 'medicines/detail.html'


medicine_detail = MedicineDetailView.as_view()


@login_required
@check_for_owner
def medicine_edit(request, pk):
    medicine = get_object_or_404(Medicine, pk=pk)
    form = MedicineForm(request.POST or None, instance=medicine)
    context = {"form": form}
    if form.is_valid():
        medicine_object = form.save()
        context['form'] = MedicineForm(instance=medicine)
        context['object'] = medicine_object
        context['edited'] = True
        return render(request, "medicines/edit.html", context=context)
    return render(request, "medicines/edit.html", context=context)


class MedicineDeleteView(DeleteView):
    model = Medicine
    template_name = 'medicines/delete.html'
    success_message = 'medicine deleted'
    context_object_name = 'object'

    def get_success_url(self):
        return reverse('medicines:list')


medicine_delete = MedicineDeleteView.as_view()


class MedicineListView(ListView):
    model = Medicine
    template_name = 'index.html'
    context_object_name = 'medicines'


medicine_list = MedicineListView.as_view()

templates/medicines/create.html
{% extends 'partials/_base.html' %}
{% block title %}
    Home
{% endblock %}
{% block content %}

    {% if created %}
        Medicine created:<a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
    {% else %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add</button>
        </form>
    {% endif %}
{% endblock %}

templates/medicines/delete.html
{% extends 'partials/_base.html' %}
{% block title %}
    Delete
{% endblock %}
{% block content %}

    {#    {% if created %}#}
    {#        Medicine created:<a href="{{ object.get_absolute_url }}">{{ object.name }}</a>#}
    {#    {% else %}#}
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <a href="{{ object.get_absolute_url }}">Cancel</a>
    </form>
    {#    {% endif %}#}
{% endblock %}

templates/medicines/detail.html
{% extends 'partials/_base.html' %}
{% block title %}
    Detail
{% endblock %}
{% block content %}
    <h3>{{ medicine.name }} > {{ medicine.dosage }} > {{ medicine.frequency }}</h3>
    <h2><a href="{% url 'medicines:edit' medicine.pk %}">edit</a></h2>
    <h2><a href="{% url 'medicines:delete' medicine.pk %}">delete</a></h2>
{% endblock %}

templates/medicines/edit.html
{% extends 'partials/_base.html' %}
{% block title %}
    Edit
{% endblock %}
{% block content %}
    {% if edited %}
        Medicine edited:<a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Edit</button>
    </form>
{% endblock %}